### ISSUE TITLE
Visitor.PVp.visitWithoutReset issue

### ISSUE THREAD

**Issue by esbanarango** [rwjblue/ember-cli-esnext#15]
Right now I'm having this issue when running my ember app.

````bash
File: admin/adapters/application.js
false == true
AssertionError: false == true
    at Visitor.PVp.visitWithoutReset (/Users/esbanarango/Developer/Freelance/DeepSpaceRobots/GCC/GCC4/Admin/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/esnext/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:135:12)
    at Visitor.PVp.visit (/Users/esbanarango/Developer/Freelance/DeepSpaceRobots/GCC/GCC4/Admin/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/esnext/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:117:21)
    at Function.transform (/Users/esbanarango/Developer/Freelance/DeepSpaceRobots/GCC/GCC4/Admin/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/esnext/node_modules/regenerator/lib/visit.js:31:18)
    at transform (/Users/esbanarango/Developer/Freelance/DeepSpaceRobots/GCC/GCC4/Admin/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/esnext/lib/index.js:86:23)
    at compile (/Users/esbanarango/Developer/Freelance/DeepSpaceRobots/GCC/GCC4/Admin/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/esnext/lib/index.js:33:9)
    at EsnextFilter.processString (/Users/esbanarango/Developer/Freelance/DeepSpaceRobots/GCC/GCC4/Admin/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/index.js:41:16)
    at EsnextFilter.Filter.processFile (/Users/esbanarango/Developer/Freelance/DeepSpaceRobots/GCC/GCC4/Admin/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/broccoli-filter/index.js:136:31)
    at Promise.resolve.then.catch.err.file (/Users/esbanarango/Developer/Freelance/DeepSpaceRobots/GCC/GCC4/Admin/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/broccoli-filter/index.js:82:21)
    at $$$internal$$tryCatch (/Users/esbanarango/Developer/Freelance/DeepSpaceRobots/GCC/GCC4/Admin/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:490:16)
    at $$$internal$$invokeCallback (/Users/esbanarango/Developer/Freelance/DeepSpaceRobots/GCC/GCC4/Admin/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:502:17)
``````

Anyone have had this before?

**Comment by et** [comment]
This just started breaking for me today as well.

This seems to resolve it

```diff
--- a/package.json
+++ b/package.json
@@ -23,7 +23,7 @@
     "ember-cli": "0.1.5",
     "ember-cli-content-security-policy": "0.3.0",
     "ember-cli-dependency-checker": "0.0.7",
-    "ember-cli-esnext": "0.1.1",
+    "ember-cli-6to5": "0.2.1",
     "ember-cli-htmlbars": "^0.6.0",
     "ember-cli-ic-ajax": "0.1.1",
     "ember-cli-inject-live-reload": "^1.3.0",
```

**Comment by esbanarango** [comment]
It does resolve it!

Thank you @et

**Comment by et** [comment]
@rwjblue - with the recent updates from [ember-cli](https://github.com/ember-cli/ember-cli/pull/2960), is this package now deprecated? If so, can we put a notice somewhere informing of the change as this is definitely hitting other people (see [stackoverflow](http://stackoverflow.com/questions/27926632/ember-cli-ember-serve-assertionerror-false-true))
